### ISSUE TITLE
Do poprawy 2.4

### ISSUE THREAD

**Issue by kacgrzes** [patmaz/js-bootcamp-react#2]
- [x] trochę mi nie pasuje ta nazwa funkcji `getPromise`
- [x] wyrzuć zbędne `console.log`
- [x] w miejscach gdzie chcesz zalogować błędne działanie aplikacji warto skorzystać z `console.error` zamiast `console.log`
- [x] nazwy propsów `properties`, albo `contect` są za bardzo ogólnikowe
- [x] `someBoolean: true` ? `this.props.randomId` ?
- [x] funkcja, którą przekazujesz do randomId nie musi być w jednej linijce. Lepiej będzie jak ją sobie wydzielisz gdzieś osobno
- [x] kod, który uruchamia całą procedurę jest pomiędzy funkcjami `getPromise` i `render` Może przenieś go w inne miejsce (początel/koniec)? Dzięki temu nie będziemy musieli tak skakać i szukać tego fragmentu od 37 - 44

**Comment by patmaz** [comment]
poprawki: https://github.com/patmaz/js-bootcamp-react/commit/79c8c3abf9a88e9c7884e74c5ec7c62da4cf493d
pkt. 5 - to trochę zabawy z propsami będącymi booleanami i funkcjami :)
pkt. 7 - coś mi tu nie gra z numerami linijek, ale chyba wiem o co chodzi. wydzieliłem funkcję tworzącą promise'a.
